#!/usr/bin/env bash
# This script attempts to display the numbers 1 to 100, but replaces multiples of 3 with Fizz, multiples of 5 with Buzz, and multiples of 3 and 5 with FizzBuzz
i=1
while [ $i -lt 101 ]
do
    if [ $(( i % 15 )) -eq 0 ]
    then echo "FizzBuzz"
    elif [ $(( i % 3 )) -eq 0 ]
    then echo "Fizz"
    elif [ $(( i % 5 )) -eq 0 ]
    then echo "Buzz"
    else echo "$i"
    fi
done
