#!/usr/bin/env bash
# This script displays "Best School" 10 times, but also displays "Hi" after the 9th
i=1
while [ $i -lt 11 ]
do
    echo "Best School"
    if [ $i = 9 ]
    then echo "Hi"
	 continue
    fi
done
