#!/usr/bin/env bash
# This script tries to display "Best School" 10 times but instead displays "bad luck" and "good luck" for the 4th and 8th iteration respectively
i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then echo "bad luck"
    elif [ $i -eq 8 ]
	 then echo "good luck"
	 else echo "Best School"
    fi
    i=$(( i + 1 ))
done
